/**
 * File: finance_import_query_client.ts
 * Description: 以fresh Session執行Finance Import bounded GET並嚴格驗證identity與cursor。
 */
import { sessionClient } from '../auth/session_client';
import { transport } from '../shared/transport';
import { ApiDecodeError } from '../shared/typed_errors';
import { FinanceImportBatchListResponseSchema, FinanceImportManifestSchema, FinanceImportReviewPageSchema, FinanceImportRunPageSchema, financeEnvelope, type FinanceImportBatchSummary, type FinanceImportManifest, type FinanceImportReviewPage, type FinanceImportRunPage } from './finance_import_query_schemas';
import { FinanceImportQueryError, mapFinanceImportQueryError } from './finance_import_query_errors';
export interface FinanceImportQueryOptions { signal?: AbortSignal; timeoutMs?: number; baseUrl?: string; }
let correlationSequence = 0;
function nextCorrelationId(scope: string): string { correlationSequence += 1; return `${scope}-${correlationSequence.toString(36)}`; }
function options(source: FinanceImportQueryOptions | undefined, scope: string) { const token = sessionClient.getToken(); if (!token) throw new FinanceImportQueryError('FINANCE_IMPORT_UNAUTHENTICATED', '請先登入。', false, 401); return { signal: source?.signal, timeoutMs: source?.timeoutMs, baseUrl: source?.baseUrl, token, headers: { 'X-Correlation-ID': nextCorrelationId(scope) } }; }
function normalizeIdentity(value: string) { const normalized = value.trim(); if (!normalized) throw new FinanceImportQueryError('FINANCE_IMPORT_VALIDATION', 'batch identity不得為空。'); return normalized; }
function assertPageCursor(ids: readonly number[], cursor: number | null, pageSize: number, code: string, label: string): void { const expected = ids.length === pageSize ? ids[ids.length - 1] ?? null : null; if (cursor !== expected) throw new FinanceImportQueryError(code, `${label} cursor與回應頁面範圍不一致。`); }
async function decode<T>(promise: Promise<unknown>, schema: ReturnType<typeof financeEnvelope>, label: string): Promise<T> { try { const raw = await promise; const parsed = schema.safeParse(raw); if (!parsed.success) throw new ApiDecodeError(`${label}回應結構異常。`, parsed.error.issues.map((issue) => ({ path: issue.path.join('.'), message: issue.message, code: issue.code })), raw); if (!parsed.data.success) throw new FinanceImportQueryError('FINANCE_IMPORT_FAILURE', parsed.data.error ?? parsed.data.message); return parsed.data.data as T; } catch (error) { throw mapFinanceImportQueryError(error); } }
export const financeImportQueryClient = {
  async listBatches(query: { limit?: number; beforeBatchId?: number } = {}, source?: FinanceImportQueryOptions): Promise<FinanceImportBatchSummary[]> {
    const limit = query.limit ?? 50; if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new FinanceImportQueryError('FINANCE_IMPORT_VALIDATION', 'limit必須介於1至100。');
    if (query.beforeBatchId !== undefined && (!Number.isInteger(query.beforeBatchId) || query.beforeBatchId <= 0)) throw new FinanceImportQueryError('FINANCE_IMPORT_VALIDATION', 'beforeBatchId必須是正整數。');
    try { const raw = await transport.get<unknown>('/api/v1/finance-import/batches', { ...options(source, 'finance-import-batches'), params: { limit, before_batch_id: query.beforeBatchId } }); const parsed = FinanceImportBatchListResponseSchema.safeParse(raw); if (!parsed.success) throw new ApiDecodeError('Finance Import批次回應結構異常。', parsed.error.issues.map((issue) => ({ path: issue.path.join('.'), message: issue.message, code: issue.code })), raw); if (!parsed.data.success) throw new FinanceImportQueryError('FINANCE_IMPORT_FAILURE', parsed.data.error ?? parsed.data.message); const ids = parsed.data.data.map((item) => item.batch_id); if (new Set(ids).size !== ids.length) throw new FinanceImportQueryError('FINANCE_IMPORT_DUPLICATE_BATCH', 'batch id重複。'); const identities = parsed.data.data.flatMap((item) => item.batch_identity === null ? [] : [item.batch_identity]); if (identities.some((item) => !item.trim() || item !== item.trim())) throw new FinanceImportQueryError('FINANCE_IMPORT_INVALID_BATCH_IDENTITY', 'batch identity必須是canonical非空文字。'); if (new Set(identities).size !== identities.length) throw new FinanceImportQueryError('FINANCE_IMPORT_DUPLICATE_BATCH_IDENTITY', 'batch identity重複。'); return parsed.data.data; } catch (error) { throw mapFinanceImportQueryError(error); }
  },
  async getManifest(batchIdentity: string, source?: FinanceImportQueryOptions): Promise<FinanceImportManifest> { const requestedIdentity = normalizeIdentity(batchIdentity); const manifest = await decode<FinanceImportManifest>(transport.get<unknown>(`/api/v1/finance-import/batches/${encodeURIComponent(requestedIdentity)}/manifest`, options(source, 'finance-import-manifest')), financeEnvelope(FinanceImportManifestSchema), 'Manifest'); if (manifest.batch_identity !== requestedIdentity) throw new FinanceImportQueryError('FINANCE_IMPORT_MANIFEST_IDENTITY_MISMATCH', 'Manifest batch identity與request不一致。'); return manifest; },
  async listReviewRows(batchIdentity: string, source?: FinanceImportQueryOptions): Promise<FinanceImportReviewPage> { const requestedIdentity = normalizeIdentity(batchIdentity); const page = await decode<FinanceImportReviewPage>(transport.get<unknown>(`/api/v1/finance-import/batches/${encodeURIComponent(requestedIdentity)}/review-rows`, { ...options(source, 'finance-import-review'), params: { limit: 50 } }), financeEnvelope(FinanceImportReviewPageSchema), 'Review rows'); assertPageCursor(page.items.map((item) => item.row_id), page.next_after_row_id, 50, 'FINANCE_IMPORT_REVIEW_CURSOR_MISMATCH', 'Review rows'); return page; },
  async listReprocessRuns(batchIdentity: string, source?: FinanceImportQueryOptions): Promise<FinanceImportRunPage> { const requestedIdentity = normalizeIdentity(batchIdentity); const page = await decode<FinanceImportRunPage>(transport.get<unknown>(`/api/v1/finance-import/batches/${encodeURIComponent(requestedIdentity)}/reprocess-runs`, { ...options(source, 'finance-import-reprocess'), params: { limit: 25 } }), financeEnvelope(FinanceImportRunPageSchema), 'Reprocess runs'); if (page.items.some((item) => item.batch_identity !== requestedIdentity)) throw new FinanceImportQueryError('FINANCE_IMPORT_REPROCESS_IDENTITY_MISMATCH', 'Reprocess run batch identity與request不一致。'); assertPageCursor(page.items.map((item) => item.run_id), page.next_before_run_id, 25, 'FINANCE_IMPORT_REPROCESS_CURSOR_MISMATCH', 'Reprocess runs'); return page; },
};
