"""Ports for knowledge persistence, index projection, retrieval, and UoW."""

from __future__ import annotations

from typing import Protocol

from domains.knowledge_retrieval.knowledge import KnowledgeAnswer


class KnowledgeIndexGatewayPort(Protocol):
    def rebuild(self, index_version: int, published_items: tuple[dict, ...]) -> None: ...
    def answer(self, question: str, index_version: int) -> KnowledgeAnswer: ...


class KnowledgeRepositoryPort(Protocol):
    def ingest(self, command) -> tuple[int, bool]: ...
    def review(self, command) -> int: ...
    def publish(self, command) -> int: ...
    def retire(self, command) -> int: ...
    def request_index_build(self, actor_id: str, idempotency_key: str) -> int: ...
    def create_answer_request(self, command) -> tuple[int, bool]: ...
    def claim_next_job(self, worker_id: str): ...
    def published_items(self) -> tuple[dict, ...]: ...
    def ready_index_version(self) -> int | None: ...
    def complete_index(self, job_id: int, index_version: int, content_set_digest: str) -> None: ...
    def complete_answer(self, job_id: int, request_id: int, answer: KnowledgeAnswer) -> int | None: ...
    def fail_job(self, job_id: int, error_code: str, retryable: bool) -> None: ...
    def list_items(self, limit: int, lifecycle_status: str | None = None) -> tuple[dict, ...]: ...
    def get_item(self, item_id: int) -> dict | None: ...
    def list_jobs(self, limit: int, processing_status: str | None = None) -> tuple[dict, ...]: ...
    def list_indexes(self, limit: int) -> tuple[dict, ...]: ...
    def get_answer_request(self, request_id: int) -> dict | None: ...
    def retry_job(self, job_id: int, actor_id: str, idempotency_key: str) -> int: ...
    def next_due_at(self): ...


class KnowledgeUnitOfWorkPort(Protocol):
    knowledge: KnowledgeRepositoryPort
    def __enter__(self): ...
    def __exit__(self, exception_type, exception, traceback) -> bool: ...
    def commit(self) -> None: ...


__all__ = [
    "KnowledgeIndexGatewayPort",
    "KnowledgeRepositoryPort",
    "KnowledgeUnitOfWorkPort",
]
